// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRx_bLuB-mFVj4qAfwK451khsNKMDMdp0',
    appId: '1:45326367026:web:49b7fe5c0f4df9230abf2b',
    messagingSenderId: '45326367026',
    projectId: 'teammate_app-6cf47',
    authDomain: 'teammate_app-6cf47.firebaseapp.com',
    storageBucket: 'teammate_app-6cf47.firebasestorage.app',
    measurementId: 'G-5G4FZG9K0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcd0piyBPHyCLFTk35kkjvoN83rduYR0g',
    appId: '1:45326367026:android:33b3f6dcf121698c0abf2b',
    messagingSenderId: '45326367026',
    projectId: 'teammate_app-6cf47',
    storageBucket: 'teammate_app-6cf47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBunha8bZpM5o8q2FElC1h_WA4SqtPDPkQ',
    appId: '1:45326367026:ios:e74353e2e3b8b7ad0abf2b',
    messagingSenderId: '45326367026',
    projectId: 'teammate_app-6cf47',
    storageBucket: 'teammate_app-6cf47.firebasestorage.app',
    iosBundleId: 'com.example.teammate_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBunha8bZpM5o8q2FElC1h_WA4SqtPDPkQ',
    appId: '1:45326367026:ios:e74353e2e3b8b7ad0abf2b',
    messagingSenderId: '45326367026',
    projectId: 'teammate_app-6cf47',
    storageBucket: 'teammate_app-6cf47.firebasestorage.app',
    iosBundleId: 'com.example.teammate_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRx_bLuB-mFVj4qAfwK451khsNKMDMdp0',
    appId: '1:45326367026:web:99b722aef1be347f0abf2b',
    messagingSenderId: '45326367026',
    projectId: 'teammate_app-6cf47',
    authDomain: 'teammate_app-6cf47.firebaseapp.com',
    storageBucket: 'teammate_app-6cf47.firebasestorage.app',
    measurementId: 'G-Y10J5S0HSV',
  );
}
